require("prototypes/entity-robots")
require("prototypes/item-group")
require("prototypes/item-modules")
require("prototypes/item-subgroup")
require("prototypes/recipe-modules")
require("prototypes/recipe-robots")
require("prototypes/technology") --/c game.player.force.research_all_technologies()